---
# handlers file for vault
- name: restart_vault
  service:
    name: vault
    state: restarted
    # enabled: yes
    daemon_reload: yes
- name: restart_consul
  service:
    name: consul
    state: restarted
    # enabled: yes
    daemon_reload: yes
