---
# tasks file for vault configuration sender
- name: Copy systemd init file
  become: yes
  template:
    src: daemon.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
  notify: systemd_reload
- name: config file
  become: yes
  template:
    src: consul.json.j2
    dest: "{{ consul_config_path }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
- name: consul service
  service:
    name: consul
    state: started
    enabled: yes
