---
- name: Vault user variables
  include_vars: ../vars/user.yml

- name: Creating consul user group
  group: 
    name: "{{ consul_group }}"
  become: true
- name: Creating consul user
  user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "consul nologin User"
    createhome: "no"
    state: present
