---
# tasks file for common
- name: User infos include
  include_vars: ../vars/user_infos.yml
- name: Main variables include
  include_vars: ../vars/main.yml

- name: Install prerequisites
  package:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - curl
    - unzip
  become: yes

- name: Debug task for common
  import_tasks: debug.yml
- name: Create {{user_name}} user
  import_tasks: user.yml
- name: Create consul process user
  import_tasks: consul_user.yml
  when: inventory_hostname not in groups['trusted-vault']
- name: Install consul
  import_tasks: install_consul.yml
  when: inventory_hostname not in groups['trusted-vault']

