---
# tasks file for vault configuration sender
- name: Copy systemd init file
  become: yes
  template:
    src: daemon.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
- name: Create config directory
  file: 
    path: "{{ vault_config_path }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
- name: Create vault data directory
  file:
    path: "{{ vault_data_dir }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: Copy public key - HTTPS
  copy:
    src: ../ssl/vault0.crt
    dest: "{{vault_config_path}}tls.crt"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0644'

- name: Copy private key - HTTPS
  copy:
    src: ../ssl/vault0.key
    dest: "{{vault_config_path}}tls.key"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0400'

- name: config file
  become: yes
  template:
    src: vault.hcl.j2
    dest: "{{ vault_config_path }}vault.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  notify: restart_vault
