---
# tasks file for vault
- name: Vault user variables
  include_vars: ../vars/vault_user.yml
- name: Vault main variables
  include_vars: ../vars/main.yml

- name: Install prerequisites
  package:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - curl
    - unzip
    - python3-pip
  become: yes
  
#- name: Creating the default user for the server
#  include_tasks: server-user.yml
- name: Create user for vault
  include_tasks: user.yml
- name: Install vault
  include_tasks: install.yml
- name: Send files and launch vault service
  include_tasks: config.yml

