- name: Install CA package
  apt:
    name: ca-certificates
    state: present
    update_cache: yes

- name: Install JQ package
  apt:
    name: jq
    state: present
    update_cache: yes

- name: Install Curl package
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Copy certificate authority to trusted CA path
  copy:
    src: ../ssl/ca4AS.crt
    dest: '/usr/local/share/ca-certificates/'
    owner: root
    group: root
    mode: 0644
  notify:
    - Update trusted CA

- name: SSH Installation
  become: yes
  apt: name=openssh-server state=latest

- name: Download the SSH CA
  get_url:
    validate_certs: no
    url: "{{ vault.url }}{{ vault.ssh }}/public_key"
    dest: /etc/ssh/sshCA.crt
    mode: '0440'
  notify:
    - Restart SSH server

- name: Add the CA to sshd config file
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^TrustedUserCAKeys "
    line: "TrustedUserCAKeys /etc/ssh/sshCA.crt"
  notify:
    - Restart SSH server

- name: Add user principals command
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AuthorizedPrincipalsCommand "
    line: "AuthorizedPrincipalsCommand /usr/bin/echo {{ vault_group }}"
  notify:
    - Restart SSH server

- name: Add user principals user command
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AuthorizedPrincipalsCommandUser "
    line: "AuthorizedPrincipalsCommandUser root"
  notify:
    - Restart SSH server
    
- name: Add Host key in sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^HostKey "
    line: "HostKey /etc/ssh/ssh_host_rsa_key"
  notify:
    - Restart SSH server
    
- name: Add Host Certificate in sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^HostCertificate "
    line: "HostCertificate /etc/ssh/ssh_host_rsa_key-cert.pub"
  notify:
    - Restart SSH server

- name: Copy Vault host Key
  copy:
    src: ../ssl/ssh_host.key
    dest: '/etc/ssh/vault.host.key'
    owner: root
    group: root
    mode: 0400

- name: Copy SSH host sign script
  become: yes
  template:
    src: ssh.host.sign.sh.j2
    dest: '/etc/ssh/ssh.host.sign.sh'
    owner: root
    group: root
    mode: 0700

- name: Sign the host ssh key
  ansible.builtin.cron:
    name: "Sign the host ssh key"
    minute: "0"
    hour: "*"
    user: root
    job: "/etc/ssh/ssh.host.sign.sh `cat /etc/ssh/vault.host.key`"

- name: Start SSH server
  become: yes
  service: name=ssh state=started enabled=true
