---
# tasks file for vault configuration sender
- name: Copy systemd init file
  become: yes
  template:
    src: consul_daemon.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
- name: Create config directory
  file: path={{consul_config_path}} state=directory
- name: Create data directory
  file: 
    path: "{{ consul_data_dir }}" 
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
- name: config file
  become: yes
  template:
    src: consul.json.j2
    dest: "{{ consul_config_path }}consul.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    notify: restart_consul
