---
# tasks file for vault configuration sender
- name: Copy systemd init file
  become: yes
  template:
    src: daemon.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
- name: Create config directory
  file: 
    path: "{{ vault_config_path }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
- name: Create vault data directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  with_items:
    - "{{vault_data_dir}}"
    - "{{vault_data_dir}}data"

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: "{{vault_config_path}}tls.key"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: "{{vault_config_path}}tls.csr"
    privatekey_path: "{{vault_config_path}}tls.key"
    common_name: "Vault Trusted"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: Generate a Self Signed OpenSSL certificate.
  openssl_certificate:
    path: "{{vault_config_path}}tls.crt"
    privatekey_path: "{{vault_config_path}}tls.key"
    csr_path: "{{vault_config_path}}tls.csr"
    provider: selfsigned
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  
- name: config file
  become: yes
  template:
    src: vault.hcl.j2
    dest: "{{ vault_config_path }}vault.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  notify: restart_vault
