---
# tasks file for vault configuration sender
- name: Copy systemd init file
  become: yes
  template:
    src: daemon.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
- name: Create config directory
  file: 
    path: "{{ vault_config_path }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
- name: Create vault data directory
  file:
    path: "{{ vault_data_dir }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
- name: config file
  become: yes
  template:
    src: vault.hcl.j2
    dest: "{{ vault_config_path }}vault.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  notify: restart_vault
#- name: Sending vault tls certificate for trusted server
#  copy:
#    src: ../files/trusted.crt
#    dest: "{{ vault_config_path }}trusted.crt"
#    owner: "{{ vault_user }}"
#    group: "{{ vault_group }}"
#  when: inventory_hostname in groups['trusted-vault']
#- name: Sending vault tls key for trusted server
#  copy:
#    src: ../files/trusted.key
#    dest: "{{ vault_config_path }}trusted.key" 
#    owner: "{{ vault_user }}"
#    group: "{{ vault_group }}"
#  when: inventory_hostname in groups['trusted-vault']
