---
all:
  children:
    vault:
      hosts:
        192.168.100.[3:4]:
          ansible_user: vault
    trusted:
      hosts:
        192.168.100.6:
          ansible_user: vault
    host:
      hosts:
        192.168.100.2:
          ansible_user: opsi
          vault_group: opsi
        192.168.100.100:
          ansible_user: user
          vault_group: reseau
        192.168.100.200:
          ansible_user: user
          vault_group: reseau
        
