---
all:
  children:
    vault:
      hosts:
        192.168.100.[3:4]:
          ansible_user: vault
    trusted:
      hosts:
        192.168.100.6:
          ansible_user: vault
    host:
      hosts:
        opsi.4as:
          ansible_user: root
          vault_group: opsi
          dns_name: opsi.4as
        ns.4as:
          ansible_user: root
          vault_group: reseau
          dns_name: ns.4as
        dhcp.4as:
          ansible_user: root
          vault_group: reseau
          dns_name: dhcp.4as
        
