- name: Restart SSH server
  service:
    name: ssh
    state: restarted

- name: Update trusted CA
  shell: /usr/sbin/update-ca-certificates

- name: Update host SSH cert signature
  shell: "/etc/ssh/ssh.host.sign.sh `cat /etc/ssh/vault.host.key`"